// require returns the Board API object
// var board = require('board');

[NoInterfaceObject, Return_from_require]
interface Board {
    attribute string name;
    attribute string version;
}; /* Board */
