// TODO: switch "long" to "any"
callback ListenerCallback = void (long... x);

interface EventEmitter {
    this on(string event, ListenerCallback... listener);
    this addListener(string event, ListenerCallback[]... listener);
// TODO: switch "long" to "any"
    boolean emit(string event, optional long arg1, long... rest);
    this removeListener(string event, ListenerCallback listener);
    this removeAllListeners(string event);
    string[] eventNames();
    long getMaxListeners();
    ListenerCallback[] listeners(string event);
    this setMaxListeners(long max);
};
