// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
// 
//   http:// www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// require returns a FS object
// var fs = require('fs');

dictionary file_descriptor
{
    long fd;
}; // dictionary file_descriptor 

[ReturnFromRequire,  ExternalInterface=(buffer,Buffer)]
interface fs {
    file_descriptor openSync(string path, string mode);
    void closeSync(file_descriptor fd);
    void rmdirSync(string path);
    long writeSync(file_descriptor fd, Buffer data, long offset, long length, optional long position);
    long readSync(file_descriptor fd, Buffer data, long offset, long length, long position);
    void truncateSync(string path, long length);
    void mkdirSync(string path);
    string[] readdirSync(string path);
    Stat statSync(string path);
    void writeFileSync(string file, Buffer data);
}; // interface fs


interface Stat {
    boolean isFile();
    boolean isDirectory();
}; // interface Stat
