// require returns a GroveLCD object
// var grove_lcd = require('grove_lcd');

[NoInterfaceObject, Return_from_require]
interface GroveLCD {
    GroveLCDDevice init();
    attribute unsigned long GLCD_FS_8BIT_MODE;
    attribute unsigned long GLCD_FS_ROWS_2;
    attribute unsigned long GLCD_FS_ROWS_1;
    attribute unsigned long GLCD_FS_DOT_SIZE_BIG;
    attribute unsigned long GLCD_FS_DOT_SIZE_LITTLE;

    attribute unsigned long GLCD_DS_DISPLAY_ON;
    attribute unsigned long GLCD_DS_DISPLAY_OFF;
    attribute unsigned long GLCD_DS_CURSOR_ON;
    attribute unsigned long GLCD_DS_CURSOR_OFF;
    attribute unsigned long GLCD_DS_BLINK_ON;
    attribute unsigned long GLCD_DS_BLINK_OFF;

    attribute unsigned long GLCD_IS_SHIFT_INCREMENT;
    attribute unsigned long GLCD_IS_SHIFT_DECREMENT;
    attribute unsigned long GLCD_IS_ENTRY_LEFT;
    attribute unsigned long GLCD_IS_ENTRY_RIGHT;

    attribute unsigned long GROVE_RGB_WHITE;
    attribute unsigned long GROVE_RGB_RED;
    attribute unsigned long GROVE_RGB_GREEN;
    attribute unsigned long GROVE_RGB_BLUE;
};

[NoInterfaceObject]
interface GroveLCDDevice {
    void print(string text);
    void clear();
    void setCursorPos(unsigned long col, unsigned long row);
    void selectColor(unsigned long index);
    void setColor(unsigned long r, unsigned long g, unsigned long b);
    void setFunction(unsigned long config);
    unsigned long getFunction();
    void setDisplayState(unsigned long config);
    unsigned long getDisplayState();
};
