// require returns a GroveLCD object
// var grove_lcd = require('grove_lcd');


enum groveLCDSettings {
    "GLCD_FS_8BIT_MODE",
    "GLCD_FS_ROWS_2",
    "GLCD_FS_ROWS_1",
    "GLCD_FS_DOT_SIZE_BIG",
    "GLCD_FS_DOT_SIZE_LITTLE",

    "GLCD_DS_DISPLAY_ON",
    "GLCD_DS_DISPLAY_OFF",
    "GLCD_DS_CURSOR_ON",
    "GLCD_DS_CURSOR_OFF",
    "GLCD_DS_BLINK_ON",
    "GLCD_DS_BLINK_OFF",

    "GLCD_IS_SHIFT_INCREMENT",
    "GLCD_IS_SHIFT_DECREMENT",
    "GLCD_IS_ENTRY_LEFT",
    "GLCD_IS_ENTRY_RIGHT",

    "GROVE_RGB_WHITE",
    "GROVE_RGB_RED",
    "GROVE_RGB_GREEN",
    "GROVE_RGB_BLUE"
}; /* groveLCDSettings */

[NoInterfaceObject]
interface GroveLCD {
    GroveLCDDevice init();
    attribute groveLCDSettings setting;
};

[NoInterfaceObject]
interface GroveLCDDevice {
    void print(string text);
    void clear();
    void setCursorPos(unsigned long col, unsigned long row);
    void selectColor(unsigned long index);
    void setColor(unsigned long r, unsigned long g, unsigned long b);
    void setFunction(unsigned long config);
    unsigned long getFunction();
    void setDisplayState(unsigned long config);
    unsigned long getDisplayState();
    void setInputState(unsigned long config);
    unsigned long getInputState();
};
