// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
// 
//   http:// www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// require returns an K64FPins object
// var pins = require('k64f_pins');

[NoInterfaceObject]
interface K64FPins {
    attribute unsigned long D0;
    attribute unsigned long D1;
    attribute unsigned long D2;
    attribute unsigned long D3;
    attribute unsigned long D4;
    attribute unsigned long D5;
    attribute unsigned long D6;
    attribute unsigned long D7;
    attribute unsigned long D8;
    attribute unsigned long D9;
    attribute unsigned long D10;
    attribute unsigned long D11;
    attribute unsigned long D12;
    attribute unsigned long D13;
    attribute unsigned long D14;
    attribute unsigned long D15;

    attribute unsigned long LEDR;
    attribute unsigned long LEDG;
    attribute unsigned long LEDB;

    attribute unsigned long SW2;
    attribute unsigned long SW3;

    attribute unsigned long PWM0;
    attribute unsigned long PWM1;
    attribute unsigned long PWM2;
    attribute unsigned long PWM3;
    attribute unsigned long PWM4;
    attribute unsigned long PWM5;
    attribute unsigned long PWM6;
    attribute unsigned long PWM7;
    attribute unsigned long PWM8;
    attribute unsigned long PWM9;

    attribute unsigned long A0;
    attribute unsigned long A1;
    attribute unsigned long A2;
    attribute unsigned long A3;
    attribute unsigned long A4;
    attribute unsigned long A5;
};
