// require returns a webusb object
// var webusb = require('webusb');

[Return_from_require, ExternalInterface=(buffer, Buffer)]
interface webusb {
    // NOTE: I don't know how to do "read"...
    void setURL(string url);
    void write(Buffer buf);
}; /* webusb interface */
