
enum type_sent_in {"BOOLEAN_T",
		   "BYTE_T",
		   "OCTET_T",
		   "SHORT_T",
		   "UNSIGNEDSHORT_T",
		   "LONG_T",
		   "UNSIGNEDSHORT_T",
		   "LONGLONG_T",
		   "UNSIGNEDLONGLONG_T",
		   "FLOAT_T",
		   "DOUBLE_T",
		   "STRING_T"
}; /* type_sent_in enum */


interface any_type_test {
    any do_something(type_sent_in arg1_type,
		     any          arg1,
		     type_sent_in arg2_type,
		     any          arg2);
}; /* any_type_test interface */
