var anything = new any_type_test();

var int81 = 1;
var int82 = 2;
var int8_sum = anything.do_something("BYTE_T", int81, "BYTE_T", int82);
print("sum of int8s "+ int81 + " and " + int82 + " = " + int8_sum + "\n");
 
var bool_value1 = (10 > 9);
var bool_value2 = (10 > 9);
var boolean_and = anything.do_something("BOOLEAN_T", bool_value1, "BOOLEAN_T", bool_value2);
print("and of boolean values " + bool_value1 + " and " + bool_value2 + " = " + boolean_and + "\n");
var string1 = "this";
var string2 = "and this";
var concatenation = anything.do_something("STRING_T", string1, "STRING_T", string2);
print("concatention of \"" + string1 + "\" and \"" + string2 + "\" = \"" + concatenation + "\"" + "\n");
var float_1 = 1.5;
var float_2 = 2.3;
var float_sum = anything.do_something("FLOAT_T", float_1, "FLOAT_T", float_2);
print("sum of floats " + float_1 + " and " + float_2 + " = " + float_sum);
