[ExternalType=(separate3, separate3)]
dictionary separate4 {
    separate3 separate3_field;
    octet separate4_octet;
}; 


interface separate_interface {
    void show_object(unsigned long x, long y, separate4 separate4_dict);
};
