#!/bin/sh
if [ ! $# -eq 2 ]
then
    echo "Usage: "`basename $0`" <directory of generator> <directory of Jerryscript>"
else
    generator_dir=`realpath $1`
    jerryscript_dir=`realpath $2`
    rm -rf any_type_test

    $generator_dir/generate.js --debug_printing --output_utility_files --package=any_type_test $generator_dir/unit_tests/any_type_test/any_type_test.idl

    cp $generator_dir/unit_tests/any_type_test/any_type_test_stubs.c any_type_test/.

   gcc -g --std=c99 -I$generator_dir/jerry-port/default/include/ -I./any_type_test -I$jerryscript_dir/jerry-port/default/include -I$jerryscript_dir/jerry-core/include -I$jerryscript_dir/jerry-ext/include -I$jerryscript_dir/jerry-ext/include/jerryscript-ext/ -I.  $generator_dir/unit_tests/any_type_test/any_type_test_demo.c any_type_test/*.c -o any_type_test/a.out $jerryscript_dir/build/lib/libjerry-core.a $jerryscript_dir/build/lib/libjerry-ext.a $jerryscript_dir/build/lib/libjerry-port-default.a -lm

    ./any_type_test/a.out >&! any_type_test.results
    diff any_type_test.results $generator_dir/unit_tests/any_type_test/expected_results 
fi
