#!/bin/sh
if [ ! $# -eq 3 ]
then
    echo "Usage: "`basename $0`" <directory of generator> <directory of Jerryscript> <.idl file directory>"
else
    generator_dir=`realpath $1`
    tests_dir=$generator_dir/unit_tests
    jerryscript_dir=`realpath $2`
    idl_dir=$3
    this_test_dir=$tests_dir/$idl_dir

# see if there's a specialized "main" routine for this test
# if there is, then it won't take an input file...
    main_file_exists=`ls $this_test_dir/*_main*.c 2> /dev/null `
echo "MAIN_FILE_EXISTS = >"$main_file_exists"<"
    if [ -n "$main_file_exists" ]
    then
        main_file=$main_file_exists
	input_script=""
    else
	main_file=$tests_dir/template/main_jerrygen.c 
	input_script=$this_test_dir/input.script
    fi
echo "    MAIN_FILE = >"$main_file"<"
echo "    INPUT_SCRIPT = >"$input_script"<"

# if the directory has neither a main nor an input script, we're
# looking to find compilation errors, so just capture those
    if [ -z "$main_file_exists" -a ! -e "$input_script" ]
    then

   echo "$generator_dir/generate.js --debug_printing --stubs=overwrite --output_utility_files --package=$idl_dir $this_test_dir/$idl_dir.idl > ./${idl_dir}_results 2>&1"
         $generator_dir/generate.js --debug_printing --stubs=overwrite --output_utility_files --package=$idl_dir $this_test_dir/$idl_dir.idl > ./${idl_dir}_results 2>&1
echo "diff ./${idl_dir}_results $this_test_dir/expected_results "
        diff ./${idl_dir}_results $this_test_dir/expected_results 
echo "done diff'ing"

    else

# TODO: what if there are multiple files to include?
	if [ -e "$this_test_dir/includes.idl" ]
	then
	    include_string="--include=$this_test_dir/includes.idl"
	else
	    include_string=""
	fi
echo "$generator_dir/generate.js $include_string --debug_printing --stubs=overwrite --output_utility_files --package=$idl_dir $this_test_dir/$idl_dir.idl"
        $generator_dir/generate.js $include_string --debug_printing --stubs=overwrite --output_utility_files --package=$idl_dir $this_test_dir/$idl_dir.idl
echo "copying"
        cp $this_test_dir/*_stubs.c $idl_dir/. 2> /dev/null
echo "done copying."

# KLUDGE!  TODO: make running a special script a general function
        if [ $idl_dir = "inheritance_test" ]
	then
       echo "$generator_dir/generate.js --debug_printing --stubs=overwrite --package=inheritance_test $this_test_dir/includes.idl"
	     $generator_dir/generate.js --debug_printing --stubs=overwrite --package=inheritance_test $this_test_dir/includes.idl
	     $this_test_dir/inject_stubs.script inheritance_test $this_test_dir/inject_print_my_name_code.awk
	elif [ $idl_dir = "separates_test" ]
	then
	    for i in `ls $this_test_dir/separates_test[2-4].idl `
	    do
  echo "$generator_dir/generate.js $include_string --debug_printing --stubs=overwrite --package=$idl_dir $this_test_dir/$i"
                $generator_dir/generate.js $include_string --debug_printing --stubs=overwrite --package=$idl_dir $i
	    done
	fi

echo "compile command:  gcc -g --std=c99 -I$generator_dir/jerry-port/default/include/ -I./$idl_dir -I$jerryscript_dir/jerry-port/default/include -I$jerryscript_dir/jerry-core/include -I$jerryscript_dir/jerry-ext/include -I$jerryscript_dir/jerry-ext/include/jerryscript-ext/ -I. $main_file $idl_dir/*.c -o $idl_dir/a.out $jerryscript_dir/build/lib/libjerry-core.a $jerryscript_dir/build/lib/libjerry-ext.a $jerryscript_dir/build/lib/libjerry-port-default.a -lm"
        gcc -g --std=c99 -I$generator_dir/jerry-port/default/include/ -I./$idl_dir -I$jerryscript_dir/jerry-port/default/include -I$jerryscript_dir/jerry-core/include -I$jerryscript_dir/jerry-ext/include -I$jerryscript_dir/jerry-ext/include/jerryscript-ext/ -I. $main_file $idl_dir/*.c -o $idl_dir/a.out $jerryscript_dir/build/lib/libjerry-core.a $jerryscript_dir/build/lib/libjerry-ext.a $jerryscript_dir/build/lib/libjerry-port-default.a -lm
echo "done compiling"

# we want to run the program if the input.script file exists or if
# the user has provided his own standalone main.c file
        if [ -e "$input_script" -o -n "$main_file_exists" ]
        then
echo "./$idl_dir/a.out $input_script > $idl_dir/results 2>&1"
            ./$idl_dir/a.out $input_script > $idl_dir/results 2>&1
echo "done running"
echo "diff $idl_dir/results $this_test_dir/expected_results "
            diff $idl_dir/results $this_test_dir/expected_results 
echo "done diff'ing"
	else
            echo "No input script."
        fi 
    fi
fi
